full_df <- read.table("household_power_consumption.txt", sep=';', header=T, na.strings ='?',colClasses=c('character','character',rep('numeric', 7)))
head(full_df)
df <- subset(full_df, Date=='1/2/2007'|Date=='2/2/2007')
rm(full_df)
png(file="plot1.png",width=480,height=480)
hist(df$Global_active_power, col = 'red', main='Global Active Power', xlab='Global Active Power (kilowatts)')
#dev.copy(png, file='plot1.png')
dev.off()