---
title: "Statistical Inference Project"
author: "jmtaysom"
date: "05/08/2015"
output: pdf_document
---
```{r load.data, echo=FALSE, results='hide'}
library(ggplot2)
library(grid)
library(gridExtra)

set.seed(0)
lambda <- 0.2
observations <- 40
trials <- 1000

expn = NULL
for (i in 1:trials) expn = c(expn, mean(rexp(observations, lambda)))

norm <- rnorm(trials,mean=1/lambda, sd = (1/lambda)/sqrt(observations))
```

# Executive summary
In this report we will explore the Central Limit Therom and how it applys to multiple draws of a sample from a population. Specifically we will look at how `r observations` means of draws of sample of size `r observations` random exponential numbers with a lambda of `r lambda` compares to `r trials` random normal observations. The random normal numbers will have a mean and standard deviation equivilant to the theoretical mean and standard deviation that we would expect for the exponential numbers. The mean and standard deviation of the population of eponential numbers are both equal to $\frac{1}{\lambda}$ or in ths case equal to `r 1/lambda`. The theoretical standard deviation of the sample will be equal to $\frac{\sigma}{\sqrt{`r observations`}}$ on in this case `r (1/lambda)/sqrt(observations)`. The actuall mean of the `r observations` is `r mean(expn)` and the standard deviation is `r sd(expn)` show that the observed values are representitive of the population according to the Central Limit Therom.


